### PR TITLE
Added an onAnimationEnd listener to the startAnimation() function

### PR DESCRIPTION
**Pull request by NicolasDucom**
I also fixed a bug in applyAnimationEndListener() that would add a new listener for every click on the button, tell me what you think !

### CODE REVIEW

**Comment by leandroBorgesFerreira** [comment]
The PR looks fine. Just one thing: This library uses 4 spaces for continuation instead of 8 spaces, just fix the lint and we can merge it =]

**Comment by leandroBorgesFerreira** [comment]
fixes #118

**Comment by leandroBorgesFerreira** [comment]
By the way, use `./gradlew build` to see the ktlint results

**Comment by NicolasDucom** [comment]
@leandroBorgesFerreira I'm having a bit of trouble seeing where the issue is with the latest build (not used to using Travis for integration testing). I'm not having any trouble when running the tests on my PC. Could you take a look at the Travis log ?

**Comment by leandroBorgesFerreira** [comment]
The instrumented tests are falling, this is a false positive and it is already present, you don't have to fix it.

**Pull request merged**
