### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yazdipour**
Cleaner Markdown

### CODE REVIEW

**Comment by leandroBorgesFerreira** [comment]
Thanks for the contribution. I'll take a look on this next week.

**Comment by yazdipour** [comment]
@leandroBorgesFerreira 
I didn't change much. It's just a little Markdown clean up in README file.

Screenshot_20190421-143210

**Comment by leandroBorgesFerreira** [comment]
Sorry for the delay. I just moved to Berlin, coming from Brazil and there's a lot going on lately.

**Comment by leandroBorgesFerreira** [comment]
Merged! Thanks for your contribution to this library!

**Pull request merged**
